---
title: "Material"
date: today
---

Below you will find the material for the course.

## Session 1
<iframe src="materials/session1.html" width="100%" height="300px" style="border: none;"></iframe>

## Session 2
<iframe src="materials/session2.html" width="100%" height="300px" style="border: none;"></iframe>

## Session 3
<iframe src="materials/session3.html" width="100%" height="300px" style="border: none;"></iframe>


## Discussion questions

::: {.callout-warning icon=false}

## Question 1

You have a fantastic new idea for novel web platform but it's hard to describe in words.

**What mechanisms could you use to convey what the platform is meant to do?**

Consider:

* What is your use-case and how would you communicate it?
* What is the minimum information deemed necessary to show its potential use?
* *An image is worth 1000 words*
:::

::: {.callout-warning icon=false}

## Question 2

Your time with your present organisation is coming to an end.

**Would you like your services to outlive your stay? What strategies can you use to ensure the service remains available?**

Consider:

* Financial or human resource needs.
* Brand and relocating the service.
* Changing needs and service sunsetting.
:::

::: {.callout-warning icon=false}

## Question 3

Imagine your service has existed for three years.

**How would you convince a funder that it has been successful?**

Consider:

* What evidence would you collect?
* Which KPIs would you track?
* What stories would you tell?
:::

::: {.callout-warning icon=false}

## Question 4

The ecosystem where your service is provided changed impacting it (positively or negatively).

**How would you assess this impact and what measures could you implement to adapt?**

Consider:

* Resourcing necessary.
* Synergies with other existing services.
* Building on brand, reputation or merit for continuation and sustainability.
:::


::: {.callout-warning icon=false}

## Question 5

Imagine a user encounters a problem with your service, either a bug in the system or they just want user guidance.

**How should they contact you?**

Discuss:

* Which reporting channels would you offer?
* Which channel would you recommend as the primary route?
* How would you ensure reports are not lost?
:::


::: {.callout-warning icon=false}

## Question 6

You want to introduce a major new feature.

**How would you test it before releasing it broadly?**

Would you use:

* Prototypes
* Pilot users
* Proof-of-concepts
* A/B testing

What are the advantages and disadvantages of your chosen approach?
:::

::: {.callout-warning icon=false}

## Question 7

You ask your favourite AI assistant to edit a Python script of your data service to make it faster.

**How would you assure it still performs as expected?**

* What are the advantages and disadvantages of your chosen approach?
:::

::: {.callout-warning icon=false}

## Question 8

Have you tried to use a published software data service and it did not work? 

Discuss:

* What was the reason?
* What was the maintenance issue?
* How could it have been avoided?
:::
